OSDG-IIITH/recommender-portal

backend/app/categories/controller.py
backend/app/models/base.py
backend/app/models/category.py
backend/app/models/ratings.py
backend/app/models/responses.py
backend/app/models/user.py
backend/app/user/controller.py
backend/requirements.in

[Fixes] openapi schema proof

---

backend/app/utils/error_handlers.py

[Add] All status codes at time of HTTPException

---

backend/app/core/controller.py
backend/app/models/base.py
backend/app/models/responses.py
backend/app/models/user.py
backend/app/user/controller.py

[Addition] `like_item_route` implementation

---

backend/app/categories/controller.py
backend/app/models/category.py

[Addition] Add-item-route implementation

---

backend/app/core/controller.py

[Fix] save user server error

---

backend/app/models/base.py
backend/app/user/controller.py

[Feature] Verify and implement get_user_route

---

backend/app/categories/controller.py

[Addition] Update_item_route-fix

---

backend/app/__init__.py
backend/app/categories/controller.py
backend/app/core/controller.py
backend/app/models/category.py
backend/app/models/ratings.py
backend/app/models/user.py
backend/app/user/controller.py
backend/app/utils/db_loader.py
backend/app/utils/error_handlers.py

Backend testing

---

frontend/README.md
frontend/src/store/modules/items.js
frontend/src/store/mutation-types.js

- Forgot to add 1 instruction in frontend README. 
- mutation-types file
- [Fix] Error in addItem action

[Add] mutation-types + README instruction + Small error in addItem action

---

frontend/src/App.vue
frontend/src/api/category.js
frontend/src/store/actions.js
frontend/src/store/index.js
frontend/src/store/modules/items.js
frontend/src/store/mutation-types.js
frontend/src/store/mutations.js

- Add dummy component for testing
- Add fetchItems action implementation
- Add an item to items state to help in debugging
- Get categories api integration

[Add] Vuex template with dummy component

---

frontend/src/components/FloatingButton.vue
frontend/src/components/FormCommon.vue
frontend/src/components/FormSpecific.vue
frontend/src/components/StepperSheet.vue

[Fixes] Fab and added separate forms for creating post

---

frontend/src/store/modules/ratings.js

[Add] Mutation: ratings/ADD_RATING

---

frontend/src/store/modules/likes.js
frontend/src/store/modules/ratings.js

Implemented issue #60: DEL_LIKE mutation

---

frontend/src/store/modules/likes.js

[ADD] mutation: likes/ADD_LIKE

---

frontend/src/components/AddPost.vue
frontend/src/components/FormCommon.vue
frontend/src/components/FormSpecific.vue
frontend/src/components/Post.vue
frontend/src/components/StepperSheet.vue

[Add] Intergration Template

---

frontend/src/App.vue
frontend/src/api/helper.js
frontend/src/plugins/updateItem.js
frontend/src/store/modules/items.js
frontend/src/store/modules/ratings.js

[Add] upsertRating + [Fix] post reload on rating/like change  + [Add] dummy component 

---

frontend/src/store/modules/likes.js

[Add]upsertLike

---

frontend/src/components/Post.vue
frontend/src/components/PostDetails.vue

[Addition] Button to show details of post from db

---

frontend/src/store/modules/items.js

[Add] mutation: items/DEL_ITEM

---

frontend/src/components/Post.vue
frontend/src/store/modules/likes.js

[ADD] integrated like items

---

frontend/src/store/modules/items.js

[Add] Action: Update Item implemetation

---

frontend/src/components/StepperSheet.vue

[Fix] Circular progress for loading in overlay

---

frontend/src/components/AddItemSheet.vue
frontend/src/components/Item.vue
frontend/src/components/ItemsDisplay.vue

- [Fix] Items display on tab change
- [Fix] Rating working
This fixes #95 and fixes #96

Fixes itemDisplay and rating

---

backend/app/core/controller.py
backend/app/utils/cas.py
frontend/config/dev.env.js
frontend/src/App.vue
frontend/src/api/authToken.js
frontend/src/api/category.js
frontend/src/api/helper.js
frontend/src/api/items.js
frontend/src/api/users.js
frontend/src/plugins/updatePlugin.js
frontend/src/router/index.js
frontend/src/store/actions.js
frontend/src/store/index.js
frontend/src/store/modules/user.js
frontend/src/store/mutations.js
frontend/src/views/Home.vue
frontend/src/views/Login.vue

[Add] Basic Login/Logout System

---

frontend/src/components/ItemCommonForm.vue

This fixes #101 and fixes #102 
There was a small problem while returning errors in add form

[Add] Reset / cancel button working

---

backend/app/categories/controller.py
backend/app/models/category.py
backend/app/models/responses.py
frontend/src/components/AddItemSheet.vue
frontend/src/components/ItemCommonForm.vue

This fixes #104.
Also there was an error in add Item component

[Update] models for optional and list + [Fix] Item not adding

---

frontend/src/components/Item.vue
frontend/src/components/Navbar.vue
frontend/src/main.js
frontend/src/views/SearchPage.vue

[Add] Search Page Frontend
